import type { Topic } from '../data/topics'
import { ContentBlockRenderer } from './ContentBlockRenderer'

type TeachingPageProps = { onBack: () => void; onDashboard: () => void; topic: Topic }

export function TeachingPage({ onBack, onDashboard, topic }: TeachingPageProps) {
  const optionText = new Map(topic.options.map((option) => [option.id, option.text]))
  return <main className="teaching-page"><button className="text-button" onClick={onBack} type="button">Back to question</button><article className="teaching-content"><h1>{topic.name}</h1><section aria-labelledby="explanation-heading"><h2 id="explanation-heading">Explanation</h2><ContentBlockRenderer blocks={topic.explanation} /></section>{topic.optionRationales && <section aria-labelledby="rationales-heading"><h2 id="rationales-heading">Answer rationales</h2>{topic.optionRationales.map((rationale) => <div className="option-rationale" key={rationale.optionId}><h3>{rationale.optionId}. {optionText.get(rationale.optionId)}</h3><ContentBlockRenderer blocks={rationale.content} /></div>)}</section>}{topic.testingPoint && <aside className="teaching-callout testing-point"><h2>Testing Point</h2><p>{topic.testingPoint}</p></aside>}{topic.bottomLine && <aside className="teaching-callout bottom-line"><h2>Bottom Line</h2><p>{topic.bottomLine}</p></aside>}{topic.references && <section className="teaching-reference" aria-labelledby="references-heading"><h2 id="references-heading">References</h2><ul>{topic.references.map((reference, index) => <li key={`${index}-${reference.title}`}><span>{reference.title}</span>{reference.url ? <><br /><a href={reference.url} rel="noreferrer" target="_blank">{reference.url}</a></> : null}<div>{reference.citation}</div></li>)}</ul></section>}</article><div className="page-actions"><button className="button button-secondary" onClick={onBack} type="button">Back to question</button><button className="button button-primary" onClick={onDashboard} type="button">Return to dashboard</button></div></main>
}
